### ISSUE TITLE
Expected /opt/redmine-0.9.0/app/models/user.rb to define User 

### ISSUE THREAD

**Issue by sjmh** [bterlson/redmine-status-updates#4]
Installing via the git repo.  Currently running redmine-0.9.0 RC.

Running the migrate results in the following trace:

(in /opt/redmine-0.9.0)
*\* Invoke db:migrate_plugins (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
Expected /opt/redmine-0.9.0/app/models/user.rb to define User
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:426:in `load_missing_constant'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:80:in`const_missing'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:92:in `const_missing'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:437:in`load_missing_constant'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:96:in `const_missing'
/opt/redmine-0.9.0/app/models/project.rb:25
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:380:in`load_without_new_constant_marking'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:380:in `load_file'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in`new_constants_in'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:379:in `load_file'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:259:in`require_or_load_without_engine_additions'
/opt/redmine-0.9.0/vendor/plugins/engines/lib/engines/rails_extensions/dependencies.rb:132:in `require_or_load'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:425:in`load_missing_constant'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:80:in `const_missing'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:92:in`const_missing'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:437:in `load_missing_constant'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:96:in`const_missing'
/opt/redmine-0.9.0/app/models/principal.rb:22
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:380:in `load_without_new_constant_marking'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:380:in`load_file'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in `new_constants_in'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:379:in`load_file'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:259:in `require_or_load_without_engine_additions'
/opt/redmine-0.9.0/vendor/plugins/engines/lib/engines/rails_extensions/dependencies.rb:132:in`require_or_load'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:425:in `load_missing_constant'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:80:in`const_missing'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:92:in `const_missing'
/opt/redmine-0.9.0/app/models/user.rb:20
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:380:in`load_without_new_constant_marking'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:380:in `load_file'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in`new_constants_in'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:379:in `load_file'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:259:in`require_or_load_without_engine_additions'
/opt/redmine-0.9.0/vendor/plugins/engines/lib/engines/rails_extensions/dependencies.rb:132:in `require_or_load'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:425:in`load_missing_constant'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:80:in `const_missing'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:92:in`const_missing'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:437:in `load_missing_constant'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:80:in`const_missing'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:437:in `load_missing_constant'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:96:in`const_missing'
/opt/redmine-0.9.0/vendor/plugins/redmine-status-updates/init.rb:8:in `evaluate_init_rb'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/callbacks.rb:182:in`call'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/callbacks.rb:182:in `evaluate_method'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/callbacks.rb:166:in`call'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/callbacks.rb:90:in `run'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/callbacks.rb:90:in`each'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/callbacks.rb:90:in `send'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/callbacks.rb:90:in`run'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/callbacks.rb:276:in `run_callbacks'
/opt/redmine-0.9.0/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:51:in`send'
/opt/redmine-0.9.0/vendor/rails/actionpack/lib/action_controller/dispatcher.rb:51:in `run_prepare_callbacks'
/opt/redmine-0.9.0/config/../vendor/rails/railties/lib/initializer.rb:631:in`prepare_dispatcher'
/opt/redmine-0.9.0/config/../vendor/rails/railties/lib/initializer.rb:185:in `process'
/opt/redmine-0.9.0/config/../vendor/rails/railties/lib/initializer.rb:113:in`send'
/opt/redmine-0.9.0/config/../vendor/rails/railties/lib/initializer.rb:113:in `run'
/opt/redmine-0.9.0/config/environment.rb:20
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:156:in`require'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in `new_constants_in'
/opt/redmine-0.9.0/vendor/rails/activesupport/lib/active_support/dependencies.rb:156:in`require'
/opt/redmine-0.9.0/vendor/rails/railties/lib/tasks/misc.rake:4
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`execute'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`execute'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:238:in`synchronize'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:607:in`invoke_prerequisites'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in `each'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in`invoke_prerequisites'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:596:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:238:in`synchronize'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in`invoke'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in`top_level'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/bin/rake:19:in`load'
/usr/bin/rake:19

**Comment by mikesmullin** [comment]
same here.

**Comment by n8osapi** [comment]
same here too

**Comment by saulkeme** [comment]
still a problem with redmine 1.0.0..
see: http://www.redmine.org/boards/2/topics/9897?r=15972#message-15972

**Comment by memetical** [comment]
bump.

**Comment by JangoSteve** [comment]
I was having the same issue. Seeing as to how the last commit to this repo was 3 years ago, I created a fork/branch with the fix @saulkeme linked to, here: https://github.com/JangoSteve/redmine-status-updates/tree/user-dependency-fix
